### ISSUE TITLE
模仿github label

### ISSUE THREAD

**Issue by ohto-ai** [ohto-ai/blog#11]
```css
.label {
    color: #8b949e;
    border-color: #30363d;
    display: inline-block;
    padding: 0 7px;
    font-size: 12px;
    font-weight: 500;
    line-height: 18px;
    white-space: nowrap;
    border: 1px solid transparent;
    border-radius: 2em;
}
```
